/**
 * icons.ts – Canonical Lucide Icon Mapping Module
 * Source of Truth: docs/DESIGN.md & .claude/skills/ats-orchestrator/reference/DESIGN_TOKENS.md
 * Re-exports Lucide icons with alias mappings for all code.html Material icon references.
 */

export {
  LayoutDashboard,
  LayoutDashboard as DashboardIcon,
  Briefcase,
  Briefcase as WorkIcon,
  Users,
  Users as GroupIcon,
  Users as SupervisedUserCircleIcon,
  SquareKanban,
  SquareKanban as ViewKanbanIcon,
  ShieldCheck,
  ShieldCheck as VerifiedUserIcon,
  Settings,
  Settings as SettingsIcon,
  Search,
  Search as SearchIcon,
  Building2,
  Building2 as SwitchAccountIcon,
  Building2 as CorporateFareIcon,
  Sun,
  Sun as LightModeIcon,
  Moon,
  Moon as DarkModeIcon,
  Braces,
  Braces as DataObjectIcon,
  Layers,
  Layers as LayersIcon,
  Columns2,
  Columns2 as SplitscreenIcon,
  CheckCircle2,
  CheckCircle2 as CheckCircleIcon,
  BellRing,
  BellRing as NotificationsActiveIcon,
  UserSearch,
  UserSearch as PersonSearchIcon,
  CircleDot,
  CircleDot as RadioButtonCheckedIcon,
  Circle,
  Circle as RadioButtonUncheckedIcon,
  Zap,
  Zap as BoltIcon,
  Star,
  Star as StarIcon,
  Sparkles,
  Sparkles as AutoAwesomeIcon,
  Terminal,
  Terminal as TerminalIcon,
  LogOut,
  LogOut as LogoutIcon,
  LogOut as ExitIcon,
  X,
  X as CloseIcon,
  LoaderCircle,
  Plus,
  ArrowRight,
  GripVertical,
  Linkedin,
  Mail,
  Lock,
  Eye,
  EyeOff,
  Trash2,
  Pencil,
  RefreshCw,
  AlertTriangle,
  HelpCircle,
  Download,
  Copy,
  ExternalLink,
  ChevronDown,
  ChevronRight,
  Filter,
  Check,
  Clock,
  FileText
} from 'lucide-vue-next';
